[package]
name = "rustray"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
tonic = "0.9"
prost = "0.11"
async-trait = "0.1"
uuid = { version = "1.3", features = ["v4", "serde"] }
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jsonwebtoken = "8.1"
rand = "0.8"
tracing = "0.1"
tracing-subscriber = "0.3"
metrics = "0.20"
dashmap = "5.4"
bytes = "1.4"
num_cpus = "1.15"
rocksdb = "0.20"
nix = "0.26"
page_size = "0.5"
procfs = "0.14"
unshare = "0.7"

[dev-dependencies]
criterion = { version = "0.4", features = ["async_tokio"] }
tokio-test = "0.4"
quickcheck = "1.0"
quickcheck_macros = "1.0"
test-log = "0.2"
env_logger = "0.9"
mockall = "0.11"
proptest = "1.0"

[[bench]]
name = "benchmarks"
harness = false

[build-dependencies]
tonic-build = "0.9"

[[example]]
name = "matrix_multiply"
path = "examples/matrix/matrix_multiply.rs"

[[example]]
name = "prime_finder"
path = "examples/prime/prime_finder.rs"

[[example]]
name = "image_filter"
path = "examples/image_processing/image_filter.rs"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
debug = true

[profile.bench]
lto = true
codegen-units = 1
debug = true 