[build]
rustc-wrapper = "sccache"  # 如果安装了 sccache
jobs = 8                   # 并行编译任务数，建议设置为 CPU 核心数

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "link-arg=-fuse-ld=lld",  # 使用 lld 链接器
]

[cargo-new]
vcs = "git"

[net]
git-fetch-with-cli = true   # 使用系统 git 而不是内置的

[registries.crates-io]
protocol = "sparse"  # 使用新的 sparse protocol 