[build]
jobs = 8  # 设置为CPU核心数

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "opt-level=2",
    "-C", "debuginfo=0",
    "-C", "codegen-units=256",
]

[cargo-new]
vcs = "git"

[net]
git-fetch-with-cli = true   # 使用系统 git 而不是内置的

[registries.crates-io]
protocol = "sparse"

[source.crates-io]
replace-with = 'mirror'

[source.mirror]
registry = "sparse+https://mirrors.aliyun.com/crates.io-index/"

[registries.mirror]
index = "https://mirrors.aliyun.com/crates.io-index/"